name: bagel
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cudatoolkit=11.8
  - cudnn
  - pip
  - pip:
    - scikit-learn
    - pandas
    - tensorflow~=2.13.0
    - tensorflow-probability~=0.21.0
